### ISSUE TITLE
Failed to launch the browser process!

### ISSUE THREAD

**Issue by michelmelo** [edupoli/MyZap2.0#6]
olá viva estou com este erro em um servidor linux.
```bash
UnhandledRejection: Failed to launch the browser process!
[1098540:1098540:0805/113831.485983:ERROR:browser_main_loop.cc(586)] Failed to open an X11 connection.
[1098540:1098540:0805/113831.487444:ERROR:browser_main_loop.cc(1439)] Unable to open X display.


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/root/MyZap2.0/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:193:20)
    at Interface.<anonymous> (/root/MyZap2.0/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:183:68)
    at Interface.emit (node:events:406:35)
    at Interface.close (node:readline:586:8)
    at Socket.onend (node:readline:277:10)
    at Socket.emit (node:events:406:35)
    at endReadableNT (node:internal/streams/readable:1331:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
cleanup
```

**Comment by edupoli** [comment]
voce deve instalar o google chrome, execute os comandos abaixo

considerando que seu servidor esteja com Ubuntu server 20.04

sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
sudo apt-get update
sudo apt-get install google-chrome-stable

**Comment by michelmelo** [comment]
@edupoli eu ja tenho a primeira versao a corre na mesma maquina.

**Comment by edupoli** [comment]
Mas essa versão é diferente na versão anterior usa Google Chromiun , nessa versao utiliza-sse  Google Chrome, portanto basta executar os comandos 

wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
 sudo dpkg -i google-chrome-stable_current_amd64.deb

que vai dar certo

**Comment by michelmelo** [comment]
Ficou na mesma,
que tipo de maquina que tem o serviço a corre?
hoje tenho uma VPN na digital,

**Comment by kallario** [comment]
Boa noite, instalei o myzap2.0 executo e quando conecta dá o seguinte erro:
TypeError: Cannot read property 'user' of undefined
    at Function.start (/var/www/MyZap2.0/engines/WppConnect.js:105:64)
O que pode ser?

**Comment by kkkasio** [comment]
Tenho o mesmo problema, estou usando wsl2 no windows.
ps: algo me diz que pode ser o path de execução do puppeter.

**Comment by jhowbhz** [comment]
@kkkasio  wsl2 não use o google chrome.

**Comment by poweriguana** [comment]
> Boa noite, instalei o myzap2.0 executo e quando conecta dá o seguinte erro: TypeError: Cannot read property 'user' of undefined at Function.start (/var/www/MyZap2.0/engines/WppConnect.js:105:64) Esse erro só acontece no Whatsapp Business, no normal não. Outro detalhe, como envio mensagens?

Estou com o mesmo problema. Já tentei usar os 3 módulos, APPConenect, Venom, etc, e tenho o mesmo erro. @edupoli alguma luz?

**Comment by JackesNascimento** [comment]
> 
[kallario](https://github.com/kallario)
Eu estou usando este Script da **API Gratis** para comunicar com a MyZapp2.0 já que ambos usam a mesma API.
https://www.youtube.com/watch?v=ZU6YJQ8D4oE

**Comment by JackesNascimento** [comment]
No meu caso, também apresenta o mesmo erro ao scannear com WhatsApp Business.
Porem ao scannear com Whatsapp normal a API não reconhece o scaneamento:

Aqui ele chega gerar o QRCode, eu faço a leitura, porem a Session expira e o Browser encerra (Mesmo problema com  WPPConcect e Venom)
{"code":"2@wbHF42rsyhOaDsST4NfyEmrZ0EpuBIhM2QmWCmYv9Y+p+OxmSwD1QCT7ZhNIOz7ti/BxI+KYWTW6xw==,iSM47hL29hsGpCYnO7AuKKch5FsPPosRgUB7T1ZxAhA=,Wd9Evo1G7kI7n2GetRnI02P+XqVQpeBV6iLbLbcmNh4=,0tNmSVSvrR9NJpm+/OWLGTKV+uGp7ODUR/hPK/3HeuI="}
info:     [myzap:session] Session Unpaired
webhooks status message....
webhooks connect status....
info:     [myzap:session] Closing the page
autocloseCalled
browserClose
warn:     [myzap:session] Failed to authenticate
qrReadError
error:    [myzap:session] Auto Close Called
Auto Close Called
webhooks connect status....

Já atualizei o Chome com as instruções para nosso colega acima, já atualizei o Pacote da WPPConnect e Venom, porem fiquei na mesma.
